#!/bin/bash

if [ "$1" == "stage1" ]; then
    fdisk /dev/sda
    mkfs.ext4 /dev/sda1
    mount /dev/sda1 /mnt
    pacstrap /mnt/ base base-devel
    genfstab /mnt >> /mnt/etc/fstab
    cp $0 /mnt/
    arch-chroot /mnt
    reboot
fi

if [ "$1" == "stage2" ]; then
    vi /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8"  > /etc/locale.conf
    hwclock --systohc --utc
    echo "zathras" > /etc/hostname
    passwd
    pacman -S grub
    grub-install /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg
    exit 1
fi

if [ "$1" == "network" ]; then
    cp /etc/netctl/examples/ethernet-dhcp /etc/netctl/enp0s3
    vi /etc/netctl/enp0s3
    systemctl enable dhcpcd
    systemctl start dhcpcd
    reboot
fi

if [ "$1" == "apps" ]; then
    sudo pacman -Syu
    sudo pacman -S xorg xorg-xinit terminator firefox dmenu git lunix-headers vnc4server lightdm
    sudo git clone git://git.suckless.org/dwm
    cd dwm
    make
    sudo make install
    echo -e "#"'!'"/bin/bash\n\nexec dwm" > ~/.xinitrc
    vncserver
    vncserver -kill :1 
    rm ~/.vnc/xstartup
    echo -e "#"'!'"/bin/bash\n\nexec dwm" > ~/.vnc/xstartup
    chmod +x ~/.vnc/xstartup
    reboot
fi

if [ "$1" == "appsroot" ]; then
    pacman -Syu
    pacman -S xorg xorg-xinit terminator firefox dmenu git lunix-headers vnc4serer lightdm
    git clone git://git.suckless.org/dwm
    cd dwm
    make
    make install
    echo -e "#"'!'"/bin/bash\n\nexec dwm" > ~/.xinitrc
    vncserver
    vncserver -kill :1
    reboot
fi

if [ "$1" == "vbox" ]; then
    echo -e "\nLoad guest installs in vbox:\n"
    read 
    pacman -S virtualbox-guest-iso
    mount /dev/cdrom /mnt
    cd /mnt
    ./VBoxLinuxAdditions.run
    reboot
fi
